---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: clone
  commands:
  - git clone $DRONE_GIT_SSH_URL
- name: build
  commands:
  - echo $WEBDAV_PASSWORD > WEBDAV_PASSWORD
  - cd $DRONE_REPO_NAME && echo $GIT_SUDO | sudo -S make
  environment:
    GIT_SUDO:
      from_secret: git_sudo
    WEBDAV_PASSWORD:
      from_secret: WEBDAV_PASSWORD

node:
  machine: buildbox

---
kind: pipeline
type: exec
name: report

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: report
  commands:
  - /usr/local/bin/telegram.run

trigger:
  status:
  - success
  - failure

node:
  machine: hangar.rcmd.space

depends_on:
- default
